import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/** Tally is a command-line chatbot that helps the user keep a tally of their tasks. */
public class Tally {
    private static final String NAME = "Tally";

    /** Horizontal rule fencing off each of the chatbot's messages. */
    private static final String RULE = "_".repeat(60);

    /**
     * ASCII rendering of the chatbot's name.
     *
     * <p>ASCII rendering generated by Claude, which used figlet.
     */
    private static final String BANNER = """
             _____     _ _
            |_   _|_ _| | |_   _
              | |/ _` | | | | | |
              | | (_| | | | |_| |
              |_|\\__,_|_|_|\\__, |
                           |___/""";

    /**
     * Runs the chatbot by greeting the user, storing each task entered, listing
     * them on request, and saying goodbye once the user types "bye".
     *
     * @param args command-line arguments, which Tally does not use for now.
     */
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        List<Task> tasks = new ArrayList<>();
        say(BANNER, "Hello! I'm " + NAME + ".", "What can I do for you?");

        while (scanner.hasNextLine()) {
            String command = scanner.nextLine();
            if (command.equals("bye")) {
                break;
            } else if (command.equals("list")) {
                if (tasks.isEmpty()) {
                    say("Nothing on your tally yet.");
                } else {
                    say(formatTasks(tasks));
                }
            } else if (command.startsWith("mark ")) {
                Task task = tasks.get(parseTaskNumber(command, "mark "));
                task.markAsDone();
                say("Nice! I've marked this task as done:", task.toString());
            } else if (command.startsWith("unmark ")) {
                Task task = tasks.get(parseTaskNumber(command, "unmark "));
                task.markAsNotDone();
                say("OK, I've marked this task as not done yet:", task.toString());
            } else {
                tasks.add(new Todo(command));
                say("added: " + command);
            }
        }

        say("Bye. Hope to see you again soon!");
        scanner.close();
    }

    /**
     * Returns the list position named by a command such as "mark 2", converted
     * from the 1-based number the user types to a 0-based index.
     *
     * @param command the whole command line the user entered.
     * @param prefix the command word and its trailing space, such as "mark ".
     * @return the index of the task the command refers to.
     */
    private static int parseTaskNumber(String command, String prefix) {
        return Integer.parseInt(command.substring(prefix.length()).trim()) - 1;
    }

    /**
     * Returns the lines Tally prints in reply to "list": a heading, then one line
     * per task, each prefixed with its position counting from 1.
     *
     * @param tasks the tasks to format, in the order they were added.
     * @return the lines of the listing.
     */
    private static String[] formatTasks(List<Task> tasks) {
        String[] lines = new String[tasks.size() + 1];
        lines[0] = "Here are the tasks in your list:";
        for (int i = 0; i < tasks.size(); i++) {
            lines[i + 1] = String.format("%d.%s", i + 1, tasks.get(i));
        }
        return lines;
    }

    /**
     * Prints one of the chatbot's messages, fenced between horizontal rules and
     * followed by a blank line that separates it from the user's next command.
     *
     * @param lines the lines of the message, printed in order.
     */
    private static void say(String... lines) {
        System.out.println(RULE);
        for (String line : lines) {
            System.out.println(line);
        }
        System.out.println(RULE);
        System.out.println();
    }
}
