import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/** Tally is a command-line chatbot that helps the user keep a tally of their tasks. */
public class Tally {
    private static final String NAME = "Tally";

    /** Horizontal rule fencing off each of the chatbot's messages. */
    private static final String RULE = "_".repeat(60);

    /**
     * ASCII rendering of the chatbot's name.
     *
     * <p>ASCII rendering generated by Claude, which used figlet.
     */
    private static final String BANNER = """
             _____     _ _
            |_   _|_ _| | |_   _
              | |/ _` | | | | | |
              | | (_| | | | |_| |
              |_|\\__,_|_|_|\\__, |
                           |___/""";

    /**
     * Runs the chatbot by greeting the user, storing each task entered, listing
     * them on request, and saying goodbye once the user types "bye".
     *
     * @param args command-line arguments, which Tally does not use for now.
     */
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        List<Task> tasks = new ArrayList<>();
        say(BANNER, "Hello! I'm " + NAME + ".", "What can I do for you?");

        while (scanner.hasNextLine()) {
            String command = scanner.nextLine().trim();
            if (command.equals("bye")) {
                break;
            }
            try {
                handleCommand(command, tasks);
            } catch (TallyException exception) {
                say(exception.getMessage());
            }
        }

        say("Bye. Hope to see you again soon!");
        scanner.close();
    }

    /**
     * Carries out one command from the user.
     *
     * <p>The command word decides what happens; whatever follows it is that
     * command's arguments. Splitting the two apart is what lets Tally tell an
     * unknown command from a known one that was given nothing to work with.
     *
     * @param command the line the user typed, with surrounding spaces removed.
     * @param tasks the tally to read from and add to.
     * @throws TallyException if Tally cannot carry out the command.
     */
    private static void handleCommand(String command, List<Task> tasks) throws TallyException {
        String[] words = command.split(" ", 2);
        String keyword = words[0];
        String arguments = words.length > 1 ? words[1].trim() : "";

        switch (keyword) {
        case "list" -> {
            if (tasks.isEmpty()) {
                say("Nothing on your tally yet.");
            } else {
                say(formatTasks(tasks));
            }
        }
        case "mark" -> {
            Task task = tasks.get(Integer.parseInt(arguments) - 1);
            task.markAsDone();
            say("Nice! I've marked this task as done:", task.toString());
        }
        case "unmark" -> {
            Task task = tasks.get(Integer.parseInt(arguments) - 1);
            task.markAsNotDone();
            say("OK, I've marked this task as not done yet:", task.toString());
        }
        case "todo" -> {
            if (arguments.isEmpty()) {
                throw new TallyException("A todo needs a description. Try: todo read book");
            }
            addTask(tasks, new Todo(arguments));
        }
        case "deadline" -> {
            String[] fields = arguments.split(" /by ", 2);
            addTask(tasks, new Deadline(fields[0].trim(), fields[1].trim()));
        }
        case "event" -> {
            String[] fields = arguments.split(" /from | /to ", 3);
            addTask(tasks, new Event(fields[0].trim(), fields[1].trim(), fields[2].trim()));
        }
        default -> throw new TallyException(
                "I don't know that one. I understand: todo, deadline, event, list, mark, unmark, bye.");
        }
    }

    /**
     * Adds a task to the tally and tells the user what was recorded.
     *
     * @param tasks the tally to add to.
     * @param task the task to add.
     */
    private static void addTask(List<Task> tasks, Task task) {
        tasks.add(task);
        // AI identified grammatical error, manual fix.
        say("Got it. I've added this task:",
                task.toString(),
                String.format("Now you have %d %s in the list.",
                        tasks.size(), tasks.size() == 1 ? "task" : "tasks"));
    }

    /**
     * Returns the lines Tally prints in reply to "list": a heading, then one line
     * per task, each prefixed with its position counting from 1.
     *
     * @param tasks the tasks to format, in the order they were added.
     * @return the lines of the listing.
     */
    private static String[] formatTasks(List<Task> tasks) {
        String[] lines = new String[tasks.size() + 1];
        lines[0] = "Here are the tasks in your list:";
        for (int i = 0; i < tasks.size(); i++) {
            // AI suggested String.format instead of concatenating strings manually.
            lines[i + 1] = String.format("%d.%s", i + 1, tasks.get(i));
        }
        return lines;
    }

    /**
     * Prints one of the chatbot's messages, fenced between horizontal rules and
     * followed by a blank line that separates it from the user's next command.
     *
     * @param lines the lines of the message, printed in order.
     */
    private static void say(String... lines) {
        System.out.println(RULE);
        for (String line : lines) {
            System.out.println(line);
        }
        System.out.println(RULE);
        System.out.println();
    }
}
