package tally.ui;

import java.util.Scanner;

/**
 * Everything Tally says to the user and reads back from them.
 *
 * <p>Gathering it here means the wording and the fencing live in one place, so
 * the rest of the code decides what to say without knowing how it is laid out.
 */
public class Ui {
    /** The name the chatbot introduces itself with. */
    private static final String NAME = "Tally";

    /** Horizontal rule fencing off each of the chatbot's messages. */
    private static final String RULE = "_".repeat(60);

    /**
     * ASCII rendering of the chatbot's name.
     *
     * <p>ASCII rendering generated by Claude, which used figlet.
     */
    private static final String BANNER = """
             _____     _ _
            |_   _|_ _| | |_   _
              | |/ _` | | | | | |
              | | (_| | | | |_| |
              |_|\\__,_|_|_|\\__, |
                           |___/""";

    private final Scanner scanner;

    /** Creates a Ui that reads the user's commands from standard input. */
    public Ui() {
        this.scanner = new Scanner(System.in);
    }

    /**
     * Returns whether the user has typed another command.
     *
     * @return false once the input has ended.
     */
    public boolean hasNextCommand() {
        return scanner.hasNextLine();
    }

    /**
     * Returns the next command the user typed, with surrounding spaces removed.
     *
     * @return the command line.
     */
    public String readCommand() {
        return scanner.nextLine().trim();
    }

    /** Greets the user. */
    public void showWelcome() {
        show(BANNER, "Hello! I'm " + NAME + ".", "What can I do for you?");
    }

    /** Says goodbye. */
    public void showGoodbye() {
        show("Bye. Hope to see you again soon!");
    }

    /**
     * Reports something Tally could not do.
     *
     * @param message what went wrong, written for the user to read.
     */
    public void showError(String message) {
        show(message);
    }

    /**
     * Prints one of Tally's messages, fenced between horizontal rules and followed
     * by a blank line that separates it from the user's next command.
     *
     * @param lines the lines of the message, printed in order.
     */
    public void show(String... lines) {
        System.out.println(RULE);
        for (String line : lines) {
            System.out.println(line);
        }
        System.out.println(RULE);
        System.out.println();
    }

    /** Stops reading the user's input. */
    public void close() {
        scanner.close();
    }
}
