package tally.ui;

import java.util.Scanner;

/**
 * Everything Tally says to the user and reads back from them.
 *
 * <p>Tally's register is dry and unsparing: it states what is so, and is willing to
 * be pointed about it. The one place it drops the edge is when the user's record is at
 * risk -- a failed save, a file that cannot be read -- where a joke at their expense
 * would be both unkind and in the way of what they need to do next.
 *
 * <p>What a reply says is decided by whoever knows the answer, and handed here as
 * lines. How it is laid out is decided here alone: the rules fencing a message on the
 * console, and where the reply goes once it is made. Greeting and farewell are Tally's
 * own words rather than any command's, so they are written here.
 */
public class Ui {
    /** The name the chatbot introduces itself with. */
    private static final String NAME = "Tally";

    /** What it says for itself, once, on being started. */
    private static final String GREETING = "I keep the count. You keep the promises.";

    /** Horizontal rule fencing off each of the chatbot's messages. */
    private static final String RULE = "_".repeat(60);

    /**
     * ASCII rendering of the chatbot's name.
     *
     * <p>ASCII rendering generated by Claude, which used figlet.
     */
    private static final String BANNER = """
             _____     _ _
            |_   _|_ _| | |_   _
              | |/ _` | | | | | |
              | | (_| | | | |_| |
              |_|\\__,_|_|_|\\__, |
                           |___/""";

    private final Scanner scanner;
    private final boolean isConsole;
    private final StringBuilder pendingResponse = new StringBuilder();

    /**
     * Creates a Ui that either prints its replies or keeps them to be collected.
     *
     * <p>The graphical front end shows Tally's replies itself, so it wants them as
     * text rather than on standard output, while the console prints them as they are
     * made. Both go through this one class, so the two front ends cannot drift apart
     * in wording.
     *
     * @param isConsole whether replies are printed and commands read from standard input.
     */
    public Ui(boolean isConsole) {
        this.isConsole = isConsole;
        this.scanner = isConsole ? new Scanner(System.in) : null;
    }

    /**
     * Returns whether the user has typed another command.
     *
     * @return false once the input has ended.
     */
    public boolean hasNextCommand() {
        requireConsole();
        return scanner.hasNextLine();
    }

    /**
     * Returns the next command the user typed, with surrounding spaces removed.
     *
     * @return the command line.
     */
    public String readCommand() {
        requireConsole();
        return scanner.nextLine().trim();
    }

    /**
     * Greets the user.
     *
     * <p>The banner is a terminal flourish: it is drawn to be read in a fixed-width
     * console, and a window already carries the name in its title bar. Showing it there
     * would spend the top of a small window on a picture of a word.
     */
    public void showWelcome() {
        if (isConsole) {
            show(BANNER, NAME + ".", GREETING);
            return;
        }
        show(NAME + ".", GREETING);
    }

    /** Says goodbye. */
    public void showGoodbye() {
        show("Session ended. Your tasks did not.");
    }

    /**
     * Reports something Tally could not do.
     *
     * @param message what went wrong, written for the user to read.
     */
    public void showError(String message) {
        show(message);
    }

    /**
     * Says one of Tally's messages.
     *
     * <p>On the console it is printed, fenced between horizontal rules and followed by
     * a blank line separating it from the user's next command. For a window nothing is
     * printed; the words are gathered for the caller to collect and show instead.
     *
     * @param lines the lines of the message, in order.
     */
    public void show(String... lines) {
        assert lines.length > 0
                : "showing nothing would print a pair of rules with no message between them";
        if (!isConsole) {
            for (String line : lines) {
                pendingResponse.append(line).append(System.lineSeparator());
            }
            return;
        }
        System.out.println(RULE);
        for (String line : lines) {
            System.out.println(line);
        }
        System.out.println(RULE);
        System.out.println();
    }

    /**
     * Refuses a call that only makes sense when the user is at a terminal.
     *
     * <p>There is no scanner when Tally is answering a window, so a front end that
     * asked for one would otherwise meet a null with nothing to say for itself.
     *
     * @throws IllegalStateException if there is no console to read from.
     */
    private void requireConsole() {
        if (!isConsole) {
            throw new IllegalStateException("There is no console to read commands from;"
                    + " a window asks Tally for a reply instead.");
        }
    }

    /**
     * Returns everything said since this was last called, and forgets it.
     *
     * <p>The rules that fence a message on the console are left out: they separate
     * one reply from the next in a scrolling terminal, which a chat window already
     * does by putting each reply in its own bubble.
     *
     * @return the lines said, one per line, with no trailing newline.
     */
    public String takePendingResponse() {
        String response = pendingResponse.toString().stripTrailing();
        pendingResponse.setLength(0);
        return response;
    }

    /** Stops reading the user's input. */
    public void close() {
        requireConsole();
        scanner.close();
    }
}
